### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by JCKodel** [siqwin/mask_text_input_formatter#11]
When developing a Windows application, every time a separator is needed, the next char will be put in the first position in the separator group.

For instance, this screenshot has the mask ##.###.###/####-## and I typed 01234567890123:

![image](https://user-images.githubusercontent.com/379339/78847196-7cb59200-79e4-11ea-9c25-70bd378eccb2.png)

Works fine on Android, though.

(Flutter 1.18.0-5.0.pre.37)

**Comment by siqwin** [comment]
Can't reproduce, works fine on windows. 
It probably depends on the flutter code, try the flutter master branch.
