### ISSUE TITLE
Doesn't mask with widget keyboard

### ISSUE THREAD

**Issue by ManuLpz4** [siqwin/mask_text_input_formatter#17]
Hi 😁

I'm updating the value of TextEditingController from a widget based keyboard (buttons) but I can't get the output to be masked.

Any suggestion? Please and thank you

**Comment by jamesblasco** [comment]
If you update the TextEditingController manually you have to update also the Formatter manually
calling this function

`format.formatEditUpdate(TextEditingValue(oldValue), TextEditingValue(newValue))`

**Comment by ManuLpz4** [comment]
Thank you so much :)

**Comment by jamesblasco** [comment]
Your welcome!
