### ISSUE TITLE
Backspace if pressed stops at each mask separator [Android]

### ISSUE THREAD

**Issue by abner** [siqwin/mask_text_input_formatter#2]
First of all I would like to thank you to provide this code. It help me a lot.

I need some help with something:

When the user press the backspace key at the Android and keep it pressed, the chars are being deleted until find the first non-digit separator character. The user needs to release the backspace and press it again to starts to remove the characters again. Is it a feature or unexpected behavior? If it was implemented this way, could you help me to identify which part of the code i would change to toggle on/off this feature ?

Thanks in advance.

**Comment by Katekko** [comment]
Same here

**Comment by siqwin** [comment]
If the chars deleted using the backspace button and the changed string does not match the string after formatting then the Flutter requests that the text input control change its internal state to match the given state. 

Probably somewhere internal this leads to an interruption of the backspace pressing. If I will not format the string after deleting char then it will lead some weird results, so I don't know what I can to do with it.
