### ISSUE TITLE
InitialValue Issue

### ISSUE THREAD

**Issue by EMINBARI** [siqwin/mask_text_input_formatter#21]
I used your package to input phone number to the _TextFormField_, everything was ok till I use _initialValue_, when I navigate to another screen and then go back to input screen there is an issue

<img width="313" alt="Снимок экрана 2020-06-17 в 17 38 22" src="https://user-images.githubusercontent.com/38878208/84911808-59cceb80-b0c1-11ea-9fad-0164db811b04.png">

<img width="302" alt="Снимок экрана 2020-06-17 в 17 38 54" src="https://user-images.githubusercontent.com/38878208/84911862-6c472500-b0c1-11ea-84c6-fd7d55c0cae9.png">

**Comment by eniojosep** [comment]
Hi, this is not an error as such, but since you already have a controller in a TextFormField, you cannot have an initialvalue at the same time.

Well in my case I only have the controller to set the value you have to do 'controller.text = value' but just place the flat phone without the mask.
