### ISSUE TITLE
Mask input with a date

### ISSUE THREAD

**Issue by gilthonweapps** [siqwin/mask_text_input_formatter#25]
Hi,

How is it possible create a mask for a date?
For example, I would like to be able to enter MM/YY in a field. So MM should be between 01 and 12, and YY between 00 and 99.
How to achieve this?

`MaskTextInputFormatter(mask: '##/##');`

Regards,

**Comment by pedrohsampaioo** [comment]
I believe that the correct thing would be to leave the user free to enter the numbers and be validated if the entered value is valid in the textfield using regex
@gilthonweapps

**Comment by siqwin** [comment]
I agree with @pedrohsampaioo. 
Added example with date to sample application.
