### ISSUE TITLE
How to mask initialized value in controller?

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [siqwin/mask_text_input_formatter#26]

**Comment by Tibasa** [comment]
Same problem!

**Comment by reberthkss** [comment]
same

**Comment by ViniciusSossela** [comment]
I did this working around:

```
final startCtrl = TextEditingController(text: '03-04-2020 08:00');
final startTimeMask = MaskTextInputFormatter(mask: '##-##-#### ##:##', filter: {'#': RegExp(r'[0-9]')});

@override
  void initState() {
    super.initState();
    startTimeMask.formatEditUpdate(TextEditingValue.empty, TextEditingValue(text: startCtrl.text));
  }
```

**Comment by reberthkss** [comment]
> 
> 
> I did this working around:
> 
> ```
> final startCtrl = TextEditingController(text: '03-04-2020 08:00');
> final startTimeMask = MaskTextInputFormatter(mask: '##-##-#### ##:##', filter: {'#': RegExp(r'[0-9]')});
> 
> @override
>   void initState() {
>     super.initState();
>     startTimeMask.formatEditUpdate(TextEditingValue.empty, TextEditingValue(text: startCtrl.text));
>   }
> ```

works

**Comment by darkfoxdx** [comment]
I used this way because I didn't want to manually format it. Took it a while to figure it out.

```
TextEditingController _textController;
  final _maskFormatter = new MaskTextInputFormatter(
      mask: '## ### #####', filter: {"#": RegExp(r'[0-9]')});

  @override
  void initState() {
    _maskFormatter.formatEditUpdate(
        TextEditingValue.empty, TextEditingValue(text: widget.initialValue));
    _textController = TextEditingController(text: _maskFormatter.getMaskedText());
    super.initState();
  }
```

**Comment by siqwin** [comment]
The `initialText` parameter has been added to the formatter constructor.

**Comment by steve-cahn** [comment]
@siqwin Not working for me. I have a `TextEditingController` which has an initial value. The text then appears in the textfield, but isn't formatted. I even tried using `MaskTextInputFormatter(initialText...`. but that just made the textfield empty.
