### ISSUE TITLE
Package not installing correctly, Target of URI doesn't exist: 'package:mask_text_input_formatter/mask_text_input_formatter.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist

### ISSUE THREAD

**Issue by AlraziBashir** [siqwin/mask_text_input_formatter#27]
pubspec.yaml

`name: YourSayy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  mask_text_input_formatter: ^1.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  flutter_screenutil: ^2.1.0
  flappy_search_bar: ^1.7.2
  provider: ^4.1.3
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  rxdart: ^0.24.1
  flutter_twitter: ^1.1.3
  sign_in_with_apple: ^2.5.1
  cloud_functions: ^0.5.0
  cloud_firestore: ^0.13.7
  intl_phone_number_input: ^0.4.6+2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - 'assets/Icons/Vector.png'
  - 'assets/providing.png'
  - 'assets/Icons/Ctrb1.png'
  - 'assets/CommentButton.png'
  - 'assets/LikeButton.png'
  - 'assets/ShareButton.png'
  - 'assets/MenuIcon.png'
  - 'assets/SignInButton.png'
  - 'assets/Default.png'
  - 'assets/logoWhite 1.png'
  - 'assets/nav.png'
  - 'assets/icons.png'
  - 'assets/YoureInHeader.png'
  - 'assets/Group 325.png'
  - 'assets/ForgotPassText.png'
  - 'assets/likefist9kb.png'
  - 'assets/NORMAL.png'
  - 'assets/Skip.png'
  - 'assets/globe.png'
  - 'assets/Group 403.png'
  - 'assets/AllTheWorlds.png'
  - 'assets/YouBelong.png'
  - 'assets/BackButton.png'
  - 'assets/Next.png'
  - 'assets/CreateAccountIcon.png'
  - 'assets/EmailDescription.png'
  - 'assets/Group 475.png'
  - 'assets/UsernameIcon.png'
  - 'assets/Your password.png'
  - 'assets/UsernameInfoText.png'
  - 'PasswordRules.png'
  - 'assets/CompleteProfileHeader.png'
  - 'assets/CompleteProfileText.png'
  - 'assets/close-outline.png'
  - 'assets/Group 477.png'
  - 'assets/Group 399.png'
  - 'assets/home.png'
  - 'assets/user.png'
  - 'assets/rank.png'
  - 'assets/globe.png'
  - 'assets/alert.png'
  - 'assets/settings.png'
  - 'assets/log-outblack.png'
  - 'assets/worldglobe.png'
  - 'assets/messageicon24.png'
  - 'assets/Sayy Icon.png'
  - 'assets/VisitorAvatar.png'
  - 'assets/EmailDisclosure.png'
  - 'assets/youreinlikefist.png'
  - 'assets/Congrats.png'
  - 'assets/YoureInMessage.png'
  - 'assets/YoureInHeader.png'
  - 'assets/whtBackButton.png'
  - 'assets/editor.png'
  - 'assets/UserLevels.png'
  - 'assets/VisitorLeaderboard.png'
  - 'assets/SignupText.png'
  - 'assets/Signupbuttons.png'
  - 'assets/SayyTermsOfUse.png'
  - 'assets/LogInButton.png'
  - 'assets/EmailSignupButton.png'
  - 'assets/VisitorPoints.png'
  - 'assets/VisitorProfileLevel.png'
  - 'assets/moreicon2.png'
  - 'assets/GoogleLogo.png'
  - 'assets/TwitterLogo.png'
  - 'assets/PhoneEmailIcon.png'
  - 'assets/welcomeBack.png'
  - 'assets/SayyWhiteLogo.png'
  - 'assets/SayyBanner.png'
  - 'assets/ProfileImageBorder.png'
  - 'assets/BackBttn.png'
  - 'assets/BlueSayyLogo.png'

  fonts:
  - family: Montserrat Thin
    fonts:
      - asset: fonts/Montserrat/Montserrat-Thin.ttf
      - weight: 100
  - family: Montserrat Light
    fonts:
      - asset: fonts/Montserrat/Montserrat-Light.ttf
      - weight: 300
  - family: Montserrat Regular
    fonts:
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
      - weight: 400
  - family: Montserrat SemiBold
    fonts:
      - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
      - weight: 500
  - family: Montserrat Bold
    fonts:
      - asset: fonts/Montserrat/Montserrat-Bold.ttf
      - weight: 700
`

`PhoneSignUPScreen.dart
`

`import 'package:YourSayy/Screens/LoggedInHomeScreen.dart';
import 'package:YourSayy/Screens/VisitorHomeScreen.dart';
import 'package:YourSayy/SignUpScreen/EmailSignUpScreen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'package:mask_text_input_formatter/mask_text_input_formatter.dart';`

**Comment by siqwin** [comment]
Guide: https://pub.dev/packages/mask_text_input_formatter/install
Probably the command `flutter pub get` has not been run.
