### ISSUE TITLE
Cleared controller - Mask keeps the former input

### ISSUE THREAD

**Issue by S-Man42** [siqwin/mask_text_input_formatter#28]
Hi,

(taking the example from [https://pub.dev/packages/mask_text_input_formatter/example](https://pub.dev/packages/mask_text_input_formatter/example), changed the `_ExamplePageState`):

```
class _ExamplePageState extends State<ExamplePage> {

  var textEditingController = TextEditingController();
  var maskTextInputFormatter = MaskTextInputFormatter(mask: "#####", filter: { "#": RegExp(r'[0-9]') });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          TextField(
            controller: textEditingController,
            inputFormatters: [maskTextInputFormatter],
          ),
          FlatButton(
            child: Text('Clear'),
            onPressed: () {
              textEditingController.clear();
            },
          )
        ],
      )
    );
  }
}
```

I have a button which clears the `TextField `by clearing the controller. Well, the `TextField` seems ok, but when I enter new input, the already cleared will be appended:
![maskedit](https://user-images.githubusercontent.com/16626063/87774582-01564e80-c825-11ea-8ed6-0389110b310e.gif)

Since, with other input formatters this doesn't happen, I believe there's a problem with the `MaskTextInputFormatter`. Am I right or do I make a mistake? How can I clear the `TextField` properly?

Thanks in advance.

**Comment by ariefsn** [comment]
Hi,
is this solved?
got this bug too 😢

**Comment by S-Man42** [comment]
With help of @MuhammadAliKust I simply wrote a wrapper with a `reinitialize()` method:

```
import 'package:flutter/services.dart';
import 'package:mask_text_input_formatter/mask_text_input_formatter.dart';

class WrapperForMaskTextInputFormatter extends TextInputFormatter {
  String mask;
  Map<String, RegExp> filter;

  MaskTextInputFormatter _formatter;
  WrapperForMaskTextInputFormatter({this.mask, this.filter}) {
    reinitialize();
  }

  void reinitialize() {
    _formatter = MaskTextInputFormatter(
        mask: mask,
        filter: filter
    );
  }

  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    return _formatter.formatEditUpdate(oldValue, newValue);
  }
}
```

Now, I don't use the `MaskTextInputFormatter` directly anymore, but create a `WrapperForMaskTextInputFormatter` instead:

```
  var _maskInputFormatter = WrapperForMaskTextInputFormatter(
    mask: '#####',
    filter: {"#": RegExp(r'[0123]')}
  );
```

The `reinitialize()` method is now called by the clear button:
```
if (_controller != null)
  _controller.clear();

if (_inputFormatters != null) {
  _inputFormatters.forEach((formatter) {
    if (formatter is WrapperForMaskTextInputFormatter) {
      formatter.reinitialize();
    }
  }
});
```

**Comment by ViniOkamoto** [comment]
Yeah, thank you for your solutions! Guys, i solved this problem adding a new parameter to updateMask like a "clearText" which if it's true i don't send the last value to _formatUpdate.

**Comment by siqwin** [comment]
When clearing the text in the `TextEditingController` you must also call the `clear` method of the `MaskTextInputFormatter`.
