### ISSUE TITLE
Paste from clipboard and for example +1 mask

### ISSUE THREAD

**Issue by romatroskin** [siqwin/mask_text_input_formatter#3]
Hey! When I am using your mask text input formatter like
`MaskTextInputFormatter(mask: '+1 ###-###-####', filter: { "#": RegExp(r'[0-9]') })`
and want to paste from clipboard that already have +1, it is pasting with additional 1 at the start, so for example if I copied number like +10000110000 after paste I'll get +11000011000 instead of +10000110000 as expected to be like, any thoughts? :)

**Comment by siqwin** [comment]
Hello.
Please try the latest version.
