### ISSUE TITLE
Problem when mask start with a diferrent character

### ISSUE THREAD

**Issue by akinncar** [siqwin/mask_text_input_formatter#30]
I try to use

```dart
var maskFormatter = MaskTextInputFormatter(mask: '(##) #####-####', filter: { '#': RegExp(r'[0-9]') });
```
and

```dart
TextField(
  controller: controller,
  inputFormatters: [maskFormatter],
),
```

But when I enter the numbers, the first number duplicates
![image](https://user-images.githubusercontent.com/42688281/89221491-bcaf0f00-d5a9-11ea-872d-5dd5b6f2ead6.png)

**Comment by murilosamuel** [comment]
Same problem here @akinncar

**Comment by siqwin** [comment]
Can not reproduce. 
What device and keyboard do you use?

**Comment by ShaheemKhan** [comment]
Any fix for this?

**Comment by akinncar** [comment]
For me, update to 1.1.0 solved the problem, I will close this issue and if you have the problem again, feel free to re-open.

**Comment by rafampessoa** [comment]
Same problem here, I update to 1.1.0 and not solved for me.
