### ISSUE TITLE
Problem cleaning controller

### ISSUE THREAD

**Issue by andersonmendesdev** [siqwin/mask_text_input_formatter#31]
I discovered a problem when cleaning the controller using the clear or set empty value in the text field of the controller, when trying to fill the textformfield again the field is all filled in and if I remove the formatter from you the problem with the cache disappears.

**Comment by lukiinhas1616** [comment]
do you have a solution to this issue?

**Comment by codingwiththiago** [comment]
See that: https://github.com/siqwin/mask_text_input_formatter/issues/28

**Comment by Nico04** [comment]
Same issue here. 
There are workarounds but it would be nice it could be fixed directly :)

**Comment by arslantalha** [comment]
i have the same problem. i am using the form wihting a stepper. at this moment whenever the same mask type is used in the same stepper in different steps the input is suggesting the content of the previous field for the later parts of the textfield.

is there going to be an update on this?

**Comment by Nico04** [comment]
It's closed because it's fixed ? I can't see any published updates right now 🤔

**Comment by siqwin** [comment]
When clearing the text in the TextEditingController you must also call the clear method of the MaskTextInputFormatter. This is written in the readme. There is currently no way to sync the formatter with the controller due to #https://github.com/flutter/flutter/issues/86354.
