### ISSUE TITLE
Backspace not handled correctly

### ISSUE THREAD

**Issue by andrewwahid** [siqwin/mask_text_input_formatter#41]
When you press backspace it removes the character before the last character, and the cursor jumps just before the last character.
I can confirm that these issue only appears in flutter 1.22.5+
I think this issue is related to https://github.com/flutter/flutter/pull/67892 somehow...
_(all functionalities of textfield works as expected without the mast formatter)_

Here is the mask formatter I used to test this issue:
`var phoneMaskFormatter = new MaskTextInputFormatter(mask: '### ### ####', filter: { "#": RegExp(r'[0-9]') });`

**Comment by venkimurthy07** [comment]
Yes, Even i am also facing same issue, below is my regexp
  MaskTextInputFormatter(
            mask: '######-##-####', filter: {"#": RegExp(r'[0-9]')})

**Comment by handzup** [comment]
same issue

**Comment by siqwin** [comment]
Related to https://github.com/flutter/flutter/issues/75502

**Comment by orlandobj** [comment]
same issue. I'm using the flutter 1.27.0-2.0.pre.1 and mask_text_input_formatter: ^2.0.0-nullsafety.2

**Comment by przemyslaw-holownia** [comment]
Issue also occurs when keyboardType is set to TextInputType.datetime.

**Comment by JulioLongo** [comment]
It has been corrected?

**Comment by ThijsBoudrez** [comment]
> It has been corrected?

Tested and is working on 2.1.0-13.0.pre.86

**Comment by dmvvilela** [comment]
I am using Flutter 2.0.2 and still the problem exists

**Comment by Overman775** [comment]
https://github.com/flutter/flutter/issues/77855#issuecomment-801335050

**Comment by mateusdalmeida** [comment]
I have the same problem in flutter 2.0.2, I tested it on a new standard project, easily reproducible, the bug only happens when using a custom keyboardType with visible numbers, such as datetime, number, phone and visiblepassword

**Comment by bdlukaa** [comment]
Yeah I also have the same problem, but only with a custom keyboardType. Any fix for it?

**Comment by mateusdalmeida** [comment]
I performed tests with another package and the behavior did not replicate, so I believe that the problem is not in the flutter


 https://github.com/danilocoppi/flutter-textfield-mask

**Comment by daveols** [comment]
Confirming that I am no longer seeing this issue with the latest Flutter `beta` channel (`2.1.0-12.2.pre`) and version `1.2.1+` of this package.

**Comment by RakovskyiSerhii** [comment]
Hi, try set keyboardType to TextInputType.number. Just works fine for me

**Comment by Surio89** [comment]
still happens, especially when you press the backspace button on your pc keyboard. When i dont set the input type the backspace button on the android emulator keyboard works as expected but when i press the backspace button on my keyboard its not working as expected. May also not work in flutter web. Im using Flutter 2.0.3 and Plugin Version 1.2.1+

**Comment by aristeu13** [comment]
Has there been any update on this problem?

**Comment by bdlukaa** [comment]
I had to use another package because of this issue: https://github.com/danilocoppi/flutter-textfield-mask

**Comment by aristeu13** [comment]
I will try to downgrade the version of the flutter, if it does not work I will try another package

**Comment by bhanuka96** [comment]
> I will try to downgrade the version of the flutter, if it does not work I will try another package

use easy_mask plugin and downgrade flutter version to 1.22.6

**Comment by bhanuka96** [comment]
@amadeu01 @siqwin please check this issue and check this comment.

[issue](https://github.com/flutter/flutter/issues/80569)
[comment](https://github.com/flutter/flutter/issues/80569#issuecomment-821020859)

**Comment by jhonatanluiz** [comment]
same issue!

Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale pt-BR)
    • Flutter version 2.0.4
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

**Comment by jacopofranza** [comment]
Same issue here

**Comment by GabrielGoliveira04** [comment]
same issue!

**Comment by jacopofranza** [comment]
I solved it using flutter channel beta, so we will wait for the next stable release

**Comment by Jojoooo1** [comment]
Which version of the package are you using ?

**Comment by henrikskul** [comment]
also having this issue with Flutter 2.0.6 and package version ^2.0.0-nullsafety.2

**Comment by rustamkhon** [comment]
Same issue.
I'm using this mask:
`MaskTextInputFormatter(mask: '(##) ###-##-##', filter: {"#": RegExp(r'[0-9]')})`

Backspace removes not correctly.
But, when I change keyboardType of TextField from TextInputType.number to TextInputType.text, so it works correctly. Any idea how to fix?

**Comment by KateZakirova** [comment]
Fix https://github.com/siqwin/mask_text_input_formatter/pull/55/commits/8f7b40a41772079d34228b90fa36007f72a327cb

**Comment by ziqq** [comment]
> Fix [8f7b40a](https://github.com/siqwin/mask_text_input_formatter/commit/8f7b40a41772079d34228b90fa36007f72a327cb)

It's not work for me

https://recordit.co/HsBSm6Jzah

**Comment by bostaginting** [comment]
hi, any update on this issue? thank you.

**Comment by Saad-2002** [comment]
Facing same issue here

**Comment by ViniciusSossela** [comment]
Migrated to `https://pub.dev/packages/flutter_multi_formatter`

**Comment by DmitrySikorsky** [comment]
I have the same issue. Backspace clears all text. If you type it again, then backspace works as expected.

**Comment by siqwin** [comment]
Unfortunately, I am unable to reproduce this bug (tried on more than ten devices).
So many comments, but no one wrote some info about device / OS version / keyboard type / formatter setup / sample code...
It would be great if someone would describe in detail the entire configuration to reproduce the bug.

**Comment by mzdm** [comment]
> Unfortunately, I am unable to reproduce this bug (tried on more than ten devices). So many comments, but no one wrote some info about device / OS version / keyboard type / formatter setup / sample code... It would be great if someone would describe in detail the entire configuration to reproduce the bug.

Please see https://github.com/siqwin/mask_text_input_formatter/issues/70#issuecomment-1241633575. Occurs only on iOS

**Comment by toshiossada** [comment]
I'm facing this error, any update?
