### ISSUE TITLE
When there is nothing in the inputfield and you type fast enought, then the first digit gets replaced by the second one.

### ISSUE THREAD

**Issue by chickenlover23** [siqwin/mask_text_input_formatter#42]

**Comment by SabrinaKaren** [comment]
Hi @chickenlover23!
I am experiencing the same problem. I saw that you closed the issue, I would like to know if you found the solution, or if someone else did it.

**Comment by chickenlover23** [comment]
Hi @SabrinaKaren,
I do not really remember whether I closed the issue or not, but I solved the issue by using another package. masked_text_formatter worked perfect for me, have not had any problems with it.
