### ISSUE TITLE
Support eager formatting

### ISSUE THREAD

**Issue by steven-spiel** [siqwin/mask_text_input_formatter#44]
This is a great plugin. Thank you for simplifying TextInputFormatters.

One feature request is to have eager formatting

Given this configuration for date formatting:

```dart
MaskTextInputFormatter(
  mask: '##/##/####',
  filter: <String, RegExp>{'#': RegExp('[0-9]')},
),
```

I would expect that upon entering `01`, that the text field would add the formatting so it read `01/`. Reason being, if a user was really trying to enter in `/` after the `01`, the text field doesn't allow them to do that, which could be frustrating.

Is that doable? I think the trickiest bit might be that when using backspace, we wouldn't want to add the `/` on every text input event, or they'd never be able to delete any of the formatting. So there'd need to be some way to compare the state of the text before/after the change.

**Comment by KevinZhang19870314** [comment]
@steven-spiel Hi any solution or workaround for this? I am now facing the same requirement!

**Comment by steven-spiel** [comment]
@KevinZhang19870314 We ended up just writing our own formatter

**Comment by harkairt** [comment]
Same issue, we'd like to have
`##h ##m ##s` but the trailing `s` won't appear
