### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alectogeek** [siqwin/mask_text_input_formatter#45]
Is it possible to implement this kind of masking out of the box? If not, that would be great to be able to!
![image](https://user-images.githubusercontent.com/18165303/109416800-a42c9900-79c0-11eb-8b2f-e5c4c841ab4b.png)

**Comment by II11II** [comment]
Hi you can use this mask
```

final phoneTextFormatter = MaskTextInputFormatter(
      mask: "+7 ___ ___-__-__", filter: {"_": RegExp(r'[0-9]')});
      
      ```
