### ISSUE TITLE
maxLengthEnforced not working with mask

### ISSUE THREAD

**Issue by pedrofneves** [siqwin/mask_text_input_formatter#46]
When set maxLength to value corresponding to the mask length and maxLengthEnforced to true in TextField widget, this feature does not work as expected: when maxLength is reached if you type any character the onChange callback is called.

I've tried to use LengthLimitingTextInputFormatter too but no successs.

```
var _phoneMaskFormatter = MaskTextInputFormatter(mask: '(##) #####-####');

TextField(
              controller: _phoneController,
              inputFormatters: [
                _phoneMaskFormatter,
                LengthLimitingTextInputFormatter(15)
              ],
              keyboardType: TextInputType.number,
              maxLength: 15,
              maxLengthEnforced: true,
              onChanged: (value) {
                   debugPrint(value);
              },
            );
```

**Comment by mdeandrea-mrmilu** [comment]
`maxLengthEnforced` will be deprecate in next Flutter versions
