### ISSUE TITLE
problem when trying to erase with the backspace

### ISSUE THREAD

**Issue by carlos-cnds** [siqwin/mask_text_input_formatter#47]
I have all the numeric masks with the same problem. When pressing the backspace it does not correctly delete the characters as in the example below. It is worth noting that it is only when I set the property keyboardType = TextInputType.number.

![Mask Input Format](https://user-images.githubusercontent.com/57833992/110399341-75639200-8054-11eb-942d-3cf944bfb8b4.gif)

**Comment by siqwin** [comment]
Duplicate #41
