### ISSUE TITLE
how can we switch keyboard base on mask ?

### ISSUE THREAD

**Issue by phamminhtuan** [siqwin/mask_text_input_formatter#50]
How can we auto switch keyboard base on mask 
with my example
var maskFormatterTrailer = new MaskTextInputFormatter(mask: "####@@@@@@@",filter: {"#":RegExp(r'[A-Z]'), "@": RegExp(r'[0-9]')});
when we input the first 4 character the keyboard is character, after to number it auto switch the keyboard to number

**Comment by bhanuka96** [comment]
@phamminhtuan did you find solution for that?

**Comment by phamminhtuan** [comment]
hi @bhanuka96 
Currently I could not find the best solution for this issue, I switch keyboard type manual by the event onChanged on TextField.
onChanged: (string) {
                                                  var isChange = false;
                                                  if (string.length >= 4) {
                                                    if (textInputType !=
                                                        TextInputType.number) {
                                                      isChange = true;
                                                      setState(() {
                                                        textInputType =
                                                            TextInputType
                                                                .number;
                                                      });
                                                    }
                                                  } else {
                                                    if (textInputType !=
                                                        TextInputType.text) {
                                                      isChange = true;
                                                      setState(() {
                                                        textInputType =
                                                            TextInputType.text;
                                                      });
                                                    }
                                                  }
                                                  if (isChange) {
                                                    focusNode.unfocus();
                                                    FocusScope.of(context)
                                                        .requestFocus(
                                                            focusNode1);
                                                    Future.delayed(Duration(
                                                            milliseconds: 500))
                                                        .then((v) {
                                                      FocusScope.of(context)
                                                          .requestFocus(
                                                              focusNode);
                                                    });
                                                  }
                                                },
