### ISSUE TITLE
I find a bug when i using

### ISSUE THREAD

**Issue by mahanpyk** [siqwin/mask_text_input_formatter#53]
I a musk for **iban** number and it works perfectly when entering values ​​but it does not work properly and does not clear when we use backspase
The pattern I used is this:
`####-####-####-####-####-####`

I test on flutter 2.2 and 2.0

I have tested both versions 1.2.1 and 2.0.0-nullsafety.2 and 2.2.0 and 2.2.1.

**Comment by subinsv** [comment]
We had a similar issue. Not sure this will help.

Converting the parent widget to stateful widget and declaring the MaskTextInputFormatter as an final variable seems to solve most of the issues related to backspace and random typing issues.

it would be great if somebody can confirm this.

I am on flutter 2.2

```dart
class _MyWidgetState extends State<MyWidget> {
final MaskTextInputFormatter mask = MaskTextInputFormatter(mask: '####-####-####-####-####-####');

build() {
//use the above created mask
}
}
```

**Comment by YisusCrz** [comment]
I faced the same issue.

If you want to format an input of numbers you can fix this bug adding the keyboardType property to the TextFormField or TextField.

`final maskFormatter = new MaskTextInputFormatter(mask: '+## (###) ### ####', filter: { "#": RegExp(r'[0-9]') },);`
`TextFormField(
    keyboardType: TextInputType.phone,
    inputFormatters: [maskFormatter],
),`

I tried too formating an input of text but in that case the bug persist. I'm using Flutter 2.2.1

**Comment by mahanpyk** [comment]
I used a custom keyboard and did so by calling its converter method. At first I thought it might be because of the custom field text, and then I used the library on another project as recommended, but it was still the same problem.

**Comment by bsbilal** [comment]
that error cause could be it 'setstate' calls in 'onChanged(s)' method. check that

**Comment by mahanpyk** [comment]
> that error cause could be it 'setstate' calls in 'onChanged(s)' method. check that

it's true
But I use state management Getx
