### ISSUE TITLE
Composing region changed by the framework. restarting the input method.

### ISSUE THREAD

**Issue by edsonboldrini** [siqwin/mask_text_input_formatter#64]
I always used to use this package like this: 

![image](https://user-images.githubusercontent.com/31242886/143099162-37dfe337-25e6-473d-9fce-b8f4b7e2f1ef.png)

Recently I update my flutter from 1.22.6 to 2.5.3 and migrate to null safety.

Now this annoying behavior happens to me using this formatter above:

https://user-images.githubusercontent.com/31242886/143131001-e780c12b-c361-442d-b75b-a0a30a9ef874.mp4

Every time I type a number the keyboard turns back to letters, and the console look like this:

```
I/TextInputPlugin(16562): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper(16562): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(16562): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(16562): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(16562): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(16562): endBatchEdit on inactive InputConnection
```

Can anybody help me?

**Comment by AndreyWV** [comment]
Same Issue. Very annoying.

**Comment by mrSingh007** [comment]
is it just log or really a problem?

**Comment by edsonboldrini** [comment]
> is it just log or really a problem?

It's not just a log there is a bug too, every character type the keyboard reset to the letters keyboard

**Comment by priyankpandit** [comment]
solution?

**Comment by priyankpandit** [comment]
> I always used to use this package like this:
> 
> ![image](https://user-images.githubusercontent.com/31242886/143099162-37dfe337-25e6-473d-9fce-b8f4b7e2f1ef.png)
> 
> Recently I update my flutter from 1.22.6 to 2.5.3 and migrate to null safety.
> 
> Now this annoying behavior happens to me using this formatter above:
> 
>  video_2021-11-23_18-20-32.mp4 
> Every time I type a number the keyboard turns back to letters, and the console look like this:
> 
> ```
> I/TextInputPlugin(16562): Composing region changed by the framework. Restarting the input method.
> W/IInputConnectionWrapper(16562): beginBatchEdit on inactive InputConnection
> W/IInputConnectionWrapper(16562): getTextBeforeCursor on inactive InputConnection
> W/IInputConnectionWrapper(16562): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper(16562): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper(16562): endBatchEdit on inactive InputConnection
> ```
> 
> Can anybody help me?

have u found any solution?

**Comment by Mixron469** [comment]
Because of Gboard Text Correction, you can disable it all to avoid that in Gboard Settings...

![Screenshot_1669368288](https://user-images.githubusercontent.com/110093186/203946379-9f78cc79-2f2c-460c-8314-51ebce1f9682.png)

**Comment by maharun0** [comment]
have anyone found any solution?

**Comment by vlastachu** [comment]
`keyboardType: TextInputType.visiblePassword`
