### ISSUE TITLE
Backspace not working => formatEditUpdate returns old value

### ISSUE THREAD

**Issue by Vivacesky** [siqwin/mask_text_input_formatter#68]
Backspace doesn't work when I try remove symbols that are not filtered (see video)
https://user-images.githubusercontent.com/32546955/157032162-fdf877c0-8a42-4039-a5d4-79df50c111a1.mp4

My MaskTextInputFormatter looks like this:

```
MaskTextInputFormatter(
        mask: '###-#######-##',
        filter: {'#': RegExp(r'[0-9]')},
        type: MaskAutoCompletionType.eager,
        initialText: initialText,
      );
```

Returns oldValue in the first if check because its true
newValue ==> "111"
_lastNewValue ==> "111"
oldValue ==> "111:" (this shouldn't be returned?)

 mask_text_input_formatter.dart
```
@override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    if (_lastResValue == oldValue && newValue == _lastNewValue) {
      return oldValue;
    }
    if (oldValue.text.isEmpty) {
      _resultTextArray.clear();
    }
    _lastNewValue = newValue;
    return _lastResValue = _format(oldValue, newValue);
  }
```

**Comment by siqwin** [comment]
I couldn't reproduce it.
What device and keyboard are you using?

**Comment by Vivacesky** [comment]
I was using a Pixel 4 with the default keyboard
