### ISSUE TITLE
Clean all text when change after refocus of TextField

### ISSUE THREAD

**Issue by Hellomik2002** [siqwin/mask_text_input_formatter#69]

**Comment by foreinger** [comment]
Hi! I had the same issue, and then i'v try to pass data to textEditController and to maskFormater in the same time.
like this
`    
maskFormatter = MaskTextInputFormatter(mask: '+66 (###) ###-##-##', initialText: widget.value);
textCtrl = TextEditingController(text: maskFormatter.maskText(widget.value));
`

it's work for me

**Comment by foreinger** [comment]
full code of widget
`class _Phone extends StatefulWidget {
  const _Phone({Key? key, required this.phone}) : super(key: key);

  final String phone;

  @override
  State<_Phone> createState() => _PhoneState();
}

class _PhoneState extends State<_Phone> {
  late final MaskTextInputFormatter maskFormatter;
  late final TextEditingController textCtrl;

  @override
  void initState() {
    maskFormatter = MaskTextInputFormatter(mask: '+66 (###) ###-##-##', initialText: widget.phone);
    textCtrl = TextEditingController(text: maskFormatter.maskText(widget.phone));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final Store<AppState> store = StoreProvider.of(context);

    return TextFormField(
      validator: (_) {
        if (!maskFormatter.isFill()) {
          return StaticText.invalidPhone;
        }
        return null;
      },
      controller: textCtrl,
      inputFormatters: [maskFormatter],
      keyboardType: TextInputType.phone,
      style: Theme.of(context).textTheme.bodyText1,
      decoration: InputDecoration(
        hintText: '+66 (000) 000 0000',
        errorStyle: CustomStyles.redText12,
        hintStyle: Theme.of(context).textTheme.bodyText1,
      ),
      onChanged: (String value) => store.dispatch(SetPhoneField(phone: maskFormatter.getUnmaskedText())),
    );
  }
}`

**Comment by evklidus** [comment]
works for me:
