### ISSUE TITLE
Can't delete characters then   type: MaskAutoCompletionType.eager,

### ISSUE THREAD

**Issue by vstarbear** [siqwin/mask_text_input_formatter#70]
https://user-images.githubusercontent.com/17123675/169561380-34503726-6cec-4f40-beaa-f18d9a7f9a3a.MP4
My formatter: 

> MacAddressFormater({
>     required String? value,
>   }) : super(
>           mask: 'XX:XX:XX:XX:XX:XX',
>           initialText: value,
>           filter: {'X': RegExp(r'^[A-Z0-9]')},
>           type: MaskAutoCompletionType.eager,
>         );

        
if type MaskAutoCompletionType.lazy all is ok.
how can i delete a characters use eager type?

**Comment by Lomski** [comment]
Same behaviour on ios. On android it works fine.

**Comment by coccyx-cyst** [comment]
> https://user-images.githubusercontent.com/17123675/169561380-34503726-6cec-4f40-beaa-f18d9a7f9a3a.MP4 My formatter:
> 
> > MacAddressFormater({
> > required String? value,
> > }) : super(
> > mask: 'XX:XX:XX:XX:XX:XX',
> > initialText: value,
> > filter: {'X': RegExp(r'^[A-Z0-9]')},
> > type: MaskAutoCompletionType.eager,
> > );
> 
> if type MaskAutoCompletionType.lazy all is ok. how can i delete a characters use eager type?

Did you handled that?

Got the same issue, why is that issue closed ? @siqwin 
Bug still appears.

**Comment by coccyx-cyst** [comment]
Bug still appears in version 2.4.0 on iOS, if using ```MaskAutoCompletionType.eager``` @siqwin
