### ISSUE TITLE
[Feature Request] MaskTextInputFormatter for hh:mm

### ISSUE THREAD

**Issue by ManuelFEMartinho** [siqwin/mask_text_input_formatter#71]
Hi everyone,
 is it possible to format for hh:mm where de max value is 23:59
I've tried THIS
`final timeMaskFormatter = MaskTextInputFormatter(
      mask: 'hH:mM',
      filter: {
        'h': RegExp(r'^[0-2]$'),
        'H': RegExp(r'^[0-9]$'),
        'm': RegExp(r'^[0-5]$'),
        'M': RegExp(r'^0?[0-9]$')
      },
    );`

not sure how to manage this, 

Thanks in advance

**Comment by siqwin** [comment]
#85

**Comment by bawantha** [comment]
I think he ask about without validator ,
