### ISSUE TITLE
Updating the text directly in the controller interferes onChanged

### ISSUE THREAD

**Issue by LuDColl** [siqwin/mask_text_input_formatter#79]
I updated the text directly in the empty controller and when I edited it in onChanged it returned the empty text instead of the one I inserted:

```dart
controller.text; // show ''
controller.text = mask.maskText('new text');
controller.text; // show 'new text'

TextField(
  controller: controller,
  inputFormatters: [mask],
  onChanged: (text) {
    text; // show ''
    controller.text; // show ''
  }
)
```

I managed to make it work only when I forced the Mask's formatEditUpdate:
```dart
controller.text; // show ''
controller.text = mask.maskText('new text');
controller.text; // show 'new text'

final value = controller.value;
mask.formatEditUpdate(value, value);

TextField(
  controller: controller,
  inputFormatters: [mask],
  onChanged: (text) {
    text; // show 'new text'
    controller.text; // show 'new text'
  }
)
```
Could you fix it, so I don't have to force formatEditUpdate?

**Comment by siqwin** [comment]
Instead of using the `maskText `method, use the `initialText ` parameter of the `MaskTextInputFormatter `constructor. 
The `maskText` method can be used if you need to format text in isolation from text fields.
