### ISSUE TITLE
2.5.0 release code

### ISSUE THREAD

**Issue by azack** [siqwin/mask_text_input_formatter#80]
Hello, just noting that while there is a [2.5.0 release](https://pub.dev/packages/mask_text_input_formatter/versions) on pub.dev, the latest pushes here seem to be for 2.4.0.   For auditing, users may want to see the diffs before upgrading without having to compare the published packages.  

Also noting that the code coverage seems to be last run against 2.2 here https://app.codecov.io/gh/siqwin/mask_text_input_formatter

**Comment by siqwin** [comment]
Thanks
