### ISSUE TITLE
Masked Text with static suffix

### ISSUE THREAD

**Issue by rello86** [siqwin/mask_text_input_formatter#81]
i have the following mask 

`static var mask = MaskTextInputFormatter(
          mask: '###-###.###.### MWST',
          filter: {'#': RegExp(r'[a-zA-Z0-9]')},
          type: MaskAutoCompletionType.eager,
  );`

the suffix MWST only appear when typing.

Thanks.

**Comment by siqwin** [comment]
Try to use `suffixText` of `InputDecoration` for `TextField`.
