### ISSUE TITLE
Mask with negative sign and decimal

### ISSUE THREAD

**Issue by mat20s23** [siqwin/mask_text_input_formatter#83]
If anyone can help. I need a mascara -##,#. the - sign is optional and the comma is automatically inserted when typing the number.
Can anyone help?

**Comment by yerzhant** [comment]
@siqwin Does this formatter support numbers with decimal point + grouping? Like 1.23, 123.45, 123 456.78 and so on?

**Comment by MrErkinjon** [comment]
final _phoneInputFormatter = MaskTextInputFormatter(mask: '+998 (##) ### ## ##');
I have flutter sdk 3.13.6.
The error is not formatting when pressing numbers 8 and 9 and the value is coming to emty.

**Comment by siqwin** [comment]
Unfortunately, the plugin is not suitable for such task. I think it's suitable to use FilteringTextInputFormatter with regexp of number, and another one for formatting in the format you need.
