### ISSUE TITLE
Support multiple characters validation

### ISSUE THREAD

**Issue by JoakoV3** [siqwin/mask_text_input_formatter#85]
Is there a way to make the library suport this multiple characters validation? 

```js
MaskTextInputFormatter(
  mask: 'dd/mm/yyyy', 
  filter: {'dd': RegExp(r'[0-31]'), 'mm': RegExp(r'[0-31]'), 'yyyy': RegExp(r'[1990-2023]')}
)
```

It would be nice because it would avoid the use of validator.
I am not sure if the regex is okay, but you get the idea

**Comment by siqwin** [comment]
Check the example app, there is an example of validating a date.
