### ISSUE TITLE
There is a problem entering mask text: masktext

### ISSUE THREAD

**Issue by MrErkinjon** [siqwin/mask_text_input_formatter#89]

**Comment by MrErkinjon** [comment]
https://github.com/siqwin/mask_text_input_formatter/assets/97740214/56230359-b1e8-4b8b-a55a-92e1b7a45d47

**Comment by MrErkinjon** [comment]
after entering the phone number through the code, all the numbers are deleted when editing.

**Comment by mateus1441** [comment]
> after entering the phone number through the code, all the numbers are deleted when editing.

Same situation with me.

`TextFormField(
            keyboardType: TextInputType.number,
            inputFormatters: [
              MaskTextInputFormatter(
                  mask: '#####-###',
                  filter: {"#": RegExp(r'[0-9]')}
              )
            ],
          )`
