### ISSUE TITLE
BUG: Value is lost after programmatic change

### ISSUE THREAD

**Issue by wmadden** [siqwin/mask_text_input_formatter#91]
The MaskTextInputFormatter behaves erratically if the text field's value is modified programmatically (as opposed to by user input).

The formatter tracks its current value in the `_resultTextMasked` array and it expects that `formatEditUpdate()` will be called for each change to the text field's value. In the case when the field's value is set programmatically, that doesn't happen.

**Steps to reproduce:**

1. Create a TextField using the MaskTextInputFormatter and a TextEditingController
    * The `MaskTextInputFormatter`'s `formatEditUpdate()` method will be called with `newValue = ""`
    * `resultTextMasked` will be initialized with `[]`
2. Set the TextField's value to a string (e.g "01.02.2024 08:52") via the controller
    * At this point the TextField will read "01.02.2024 08:52"
    * The `MaskTextInputFormatter`'s `formatEditUpdate()` method **will not be called**
3. Put keyboard focus in the TextField and backspace one character
    * The `MaskTextInputFormatter`'s `formatEditUpdate()` method will be called with `newValue = "01.02.2024 08:5"`
    * It will recalculate its `resultTextMasked` as `[]`, clearing the text field

**Expected behavior:**

* After backspacing one character, the TextField should read "01.02.2024 08:5" but instead it is empty

**Comment by siqwin** [comment]
Unfortunately, I can't fix such behavior because the call of `formatEditUpdate` method comes from the `EditableText`. 
There's only an option to make a custom class of it, which I would like to avoid.
For now, the only option is to call this method manually along changing the text of the TextEditingController.

**Comment by wmadden** [comment]
You might want to document it in the README then. It was a confusing process for me at least to debug it

**Comment by Nikzed** [comment]
I believe this is crucial for package like this. It cannot be ignored.

**Comment by e22m4u** [comment]
As workaround that you can use the formatter manually
```dart
final phoneFormatter = MaskTextInputFormatter(
  mask: '+# (###) ###-##-##',
  filter: {'#': RegExp(r'[0-9]')},
);

final newValue = phoneFormatter.formatEditUpdate(
  TextEditingValue.empty,
  phoneController.value, // TextEditingController
);

phoneController.value = newValue;
```
