### ISSUE TITLE
[BUG] Does not allow you to enter text

### ISSUE THREAD

**Issue by alexei-kruk-idf** [siqwin/mask_text_input_formatter#92]
It does not allow you to enter text if you use this mask
0###### and if the second character matches the first one
Example text 0056451

**Comment by alexei-kruk-idf** [comment]
@siqwin please check the bug

**Comment by siqwin** [comment]
I couldn't reproduce it. Could you write a code example?

**Comment by alexei-kruk-idf** [comment]
I am attaching an example code and a video
<details>
  <summary>example code</summary>
  
  ```
import 'package:flutter/material.dart';
import 'package:mask_text_input_formatter/mask_text_input_formatter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            inputFormatters: [
              MaskTextInputFormatter(mask: '0######'),
            ],
          ),
        ),
      ),
    );
  }
}
  ```
  
</details>


https://github.com/siqwin/mask_text_input_formatter/assets/99738581/317174d0-929c-45e4-b614-3e4c74a4b6a1
